# Navigation
alias .='pwd'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -- -='cd -'
alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias l='ls -lah'
alias ld='ls -lh'
alias l@='ls -lah@'
alias lR='ls -lahR'
alias lt='ls -lAht'
alias lu='ls -lAhtu'
alias tree="find . -print | sed -e 's;[^/]*/;|__;g;s;__|; |;g'"

# Cmds
alias md='mkdir'
alias rd='rm -R'
alias _='sudo'
alias suroot='sudo -s'
alias zshrc='mate ~/.zshrc'
alias szshrc='source ~/.zshrc'
alias hist='fc -li 1 | less +G'
alias h='history -i'
alias -g G='| grep --color=auto -i'
alias -g LG='| less +G'
alias -g DN='> /dev/null 2>&1'
alias -g X='| xargs'
alias gs='git status'
alias gpom='git push origin master'
alias gpob='git push origin $(git rev-parse --abbrev-ref HEAD)'
alias t='todo.sh -d "$ZSH"/todo.txt/todo.cfg'

# Mac
alias doff='pmset displaysleepnow; echo Display has been turned off!'
alias lock='/System/Library/CoreServices/Menu\ Extras/user.menu/Contents/Resources/CGSession -suspend'
alias pmsg='pmset -g'
alias pmsa='pmset -g assertions'
alias flushdns='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias ports='lsof -i -P'

# Goto
alias desk='~/Desktop'
alias apps='/Applications'
alias ~lib='~/Library'
alias lib='/Library'
alias ~prefs='~/Library/Preferences'
alias ~scripts='~/Library/Scripts'
alias scripts='/Library/Scripts/$(hostname)\ Scripts'
alias tmpdir='"$TMPDIR"'
alias tmp='/private/tmp'

